<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>128c8e18-a99c-4e4f-991c-f8521d23b736</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="Google.GenAI" Version="1.8.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.30.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BolNews.Application\BolNews.Application.csproj" />
    <ProjectReference Include="..\BolNews.Infrastructure\BolNews.Infrastructure.csproj" />
    <ProjectReference Include="..\BolNews.Persistence\BolNews.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\lib\quill\" />
    <Folder Include="wwwroot\uploads\articles\content\" />
    <Folder Include="wwwroot\uploads\authors\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\AdminArea\AdminAreaJS.js" />
  </ItemGroup>

</Project>
