<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BolNews.Application\BolNews.Application.csproj" />
    <ProjectReference Include="..\BolNews.Domain\BolNews.Domain.csproj" />
    <ProjectReference Include="..\BolNews.Infrastructure\BolNews.Infrastructure.csproj" />
    <ProjectReference Include="..\BolNews.Persistence\BolNews.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\uploads\articles\content\" />
    <Folder Include="wwwroot\uploads\authors\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\AdminArea\AdminAreaJS.js" />
  </ItemGroup>

</Project>
