<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="External\" />
    <Folder Include="Caching\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BolNews.Application\BolNews.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
